minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true # no git branch as package url

allowBuilds:
  cypress: true
  esbuild: true
  sharp: true

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
