import type { Metadata } from 'next'

import './globals.css'
import Providers from './providers';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App 14',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers >
          {children}
        </Providers>
      </body>
    </html>
  )
}
